Bugfix/everest: Fix CP error handling in CbTarragonDriver (refs EVEREST-1270)
chargebyte/everest-chargebyte pull request #16
Opened 2024-12-11 09:06 UTC by FaHaGit

- Moved utils files to subdirectory linux_hw
- Introduced a new library cp for all CP-related functions
- Added a generic method for error handling (check_for_cp_errors()).
- Added a generic method to raise and clear Everest errors (process_everest_errors()).
- Refactored CP error handling in CPTarragonDriver.
- Added GTests to unit test the module methods of CPTarragonDriver and CPUtils libraries.

2024-12-12 13:22 UTC, barsnick requested changes
I will do a complete review of the testcases later.

2024-12-12 15:37 UTC, lategoodbye commented on utils/cp/CPUtils.cpp
> +                                  const int& voltage_pos_side) {
I'm not really happy about this design of this function. It's very opaque and complex. Is it possible to split?
is_cp_short_fault()
is_ventilation_fault()
is_diode_fault()
is_pilot_fault()

This should make unittest more easier.

2024-12-13 10:01 UTC, lategoodbye commented on utils/cp/CPUtils.cpp
> +            (abs(voltage_pos_side + voltage_neg_side) <= CP_ERROR_VOLTAGE_MAX_DIFF)));
```suggestion
if ((duty_cycle == 100.0 || duty_cycle == 0.0) &&
    (voltage_pos_side < CP_STATE_D_LOWER_THRESHOLD) &&
    (voltage_neg_side > -10000 /* mV */))
  return true;

if (is_nominal_duty_cycle(duty_cycle) &&
    (voltage_pos_side < CP_STATE_D_LOWER_THRESHOLD) &&
    (abs(voltage_pos_side + voltage_neg_side) <= CP_ERROR_VOLTAGE_MAX_DIFF))
 return true;
 
return false;


```

2024-12-13 10:46 UTC, barsnick approved these changes

2024-12-13 10:57 UTC, lategoodbye approved these changes
Thanks

2025-01-06 13:01 UTC, merged